### ISSUE TITLE
Options for number separation

### ISSUE THREAD

**Issue by Gerben321** [Gerben321/bike-care-tracker#11]
Use decimal point rather than comma as a number separator e.g 84.6km vs 84,6km or 16,893.88km vs 16.893,88km

**Comment by Konstantin-Levin** [comment]
User could 'set region' in profile settings which could change curreny, distance unit, number sepators etc.

**Comment by Gerben321** [comment]
Would it be enough for one region option? Or separate options for everything? So, miles/km, comma /for seperation, dollar/pound/euro for currency.

I'm thinking an option for every setting is best. For example I believe not everyone in Canada uses the same units.

**Comment by Gerben321** [comment]
Little sneak-peak of the settings:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/7666eb4e-03fd-49d6-b7fa-02e502849dd2)

**Comment by Konstantin-Levin** [comment]
Yes you're right separate options for everything would be best as there will be some people who like mix between metric / imperial. 

Those screenshots look great, exactly what I was after, thanks!

**Comment by Gerben321** [comment]
This is now live!
