### ISSUE TITLE
Custom currencies

### ISSUE THREAD

**Issue by Gerben321** [Gerben321/bike-care-tracker#14]
Ability to use different currencies other than € in the value field.

**Comment by Konstantin-Levin** [comment]
Not a big problem for me, just something that would be nice to have in the future.

**Comment by Gerben321** [comment]
This will be in the next release. Preview:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/f225dbf0-36f7-4167-b42c-b17f61bb2ad4)
The setting will be in the user settings page.

**Comment by Gerben321** [comment]
This is now live!
