### ISSUE TITLE
Components cannot be removed from the bike page

### ISSUE THREAD

**Issue by Konstantin-Levin** [Gerben321/bike-care-tracker#15]
This occurs on the bike page, which shows the list of active and inactive components. The pop-up appears with the 2 options of _close_ or _remove_ but clicking _remove_ does nothing. Tested in Chrome & Firefox desktop

<img width="547" alt="Screenshot 2024-02-03 at 21 27 43" src="https://github.com/Gerben321/bike-care-tracker/assets/155573822/15492215-082f-404b-88e5-5b910a87959f">

**Comment by Gerben321** [comment]
Sorry about that. Forgot that this wasn't working yet. I'll enable the button on the next release!

**Comment by Gerben321** [comment]
This is also fixed in the next release!
