### ISSUE TITLE
Date error when adding usage period

### ISSUE THREAD

**Issue by Konstantin-Levin** [Gerben321/bike-care-tracker#21]
When adding new usage period - after having entered the start and end dates the ‘periods installed’ page shows that the end period has been automatically changed to the current date and time. 
Though the distance and moving time appear to show correctly.

On firefox desktop

<img width="1055" alt="Screenshot 2024-02-12 at 18 13 14" src="https://github.com/Gerben321/bike-care-tracker/assets/155573822/441cdd71-33c0-4d57-bee1-f69a478d67a2">

**Comment by Gerben321** [comment]
That's strange. I'll have to dig into this one. I'll let you know when I've found it.

**Comment by Gerben321** [comment]
Thanks, found it. Fixed.
