### ISSUE TITLE
Ability to sort list of components

### ISSUE THREAD

**Issue by Konstantin-Levin** [Gerben321/bike-care-tracker#23]
Would be helpful to be able to sort the list of components for a given bike. 
For example by: date added, alphabetically, next service due.

I like the active and inactive separation of components though.

Many thanks :)

**Comment by Gerben321** [comment]
Do you want this to be a global sorting? Or different per bike?

Right now, it's displayed from old to new from top to bottom. 

I can image a dropdown above your component with the options (date, alphabet, service) would be a welcome change, especially with a huge list of components.

Sorting schedule due time is difficult though, because we have time and distance, but I can do it based on the percentage maybe. But that could be a bit slow and complex. Let me know what you think would work here.

**Comment by Konstantin-Levin** [comment]
In my opinion it would be best as a drop down selection at the top of the components list page of every bike. With _date, alphabet, service_ along with a _ascending/descending_ modifier as well. I think having the information at a glance about what services are coming up soon for each bike would be helpful for planning.

I see what you mean about the difficulty of sorting by service. If it can be done on a percentage basis as you suggest that could work well. A visual indication (like a small version from the serivce schedule page) on the same line as each component would be nice and not too cluttered? 

Something like this is what I'm picturing:
![Untitled-1](https://github.com/Gerben321/bike-care-tracker/assets/155573822/360cb552-59fb-4853-839d-df788dc4baf3)

(excuse terrible image editing)

**Comment by OleksiyRudenko** [comment]
I reckoned the time-to-next-service would be helpful ( https://github.com/Gerben321/bike-care-tracker/issues/5 )

> Sorting schedule due time is difficult though, because we have time and distance, but I can do it based on the percentage maybe. But that could be a bit slow and complex. Let me know what you think would work here.

How about time prediction by linear regression based on _n_ recent (from last 30-45 days to void seasonal bias, unless having at least 2 data points for regression requires a longer period of backtracking) log entries? Estimation of avg kms/day, moving_hrs/day should be enough to predict number of days to next service.

If Activities data is supplied to the web app raw and rendering done on FE then the same data could be used by FE to perform calculations on user's machine.

What do you think?

**Comment by Gerben321** [comment]
Thanks for the ideas. This will be a major change. I am planning to pull apart the frontend and backend in this case. But this means I have to build an API and use a new frontend library and connect those etc. So this will take a bit, but I think it will open major features.

The idea is that the server (backend) can give the information on the bike (with all components etc.) to the frontend to get it rendered on the user machine. This makes it a lot easier to do complex filtering and ordering etc, without sending hundreds of heavy queries to the server.

**Comment by Gerben321** [comment]
I've got the first version that I'm happy with and want to show!

Desktop:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/e7374be9-eb9d-43c2-a5b7-e50dce42bcbb)
Mobile:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/f529fa83-9b68-4a6b-8468-d39f597d6e27)
Mobile with drawer:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/70d4054a-206c-42a3-9034-8862cac98bb2)

So as you can see I've added the filters and ordering. On mobile there's a drawer/flyout in which the filters are shown because otherwise it would be a bit cramped.

Here are the sorting options:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/2749ff2f-1c83-49ea-aca6-b7870adbdaaf)

I'm happy with this first version. It makes it a lot easier to find something.

Let me know what you guys think!

**Comment by Gerben321** [comment]
Oh and here are the filters:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/e68c40bb-b08a-4c89-a9cb-07e2210eac40)
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/0523ac2a-3490-4850-836d-769f668f626b)
Searching:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/889a7780-25af-48fa-a0d6-1eda4f808e7b)

**Comment by Konstantin-Levin** [comment]
Nicely done, that looks fantastic! Even better than I was hoping for. The search box is a nice touch, should make it really easy to find a specific component :)

Out of curiosity will a chosen sort order be maintained upon refreshing the page or will it return to the default sort?

**Comment by Gerben321** [comment]
Thanks! I really find it useful myself too now.

Right now it defaults to the current way of displaying, but it can be something that I can store locally on the device. Or as as option if that would make more sense.

**Comment by Gerben321** [comment]
I've added saving the state of ordering/filtering on the device as well. Right now I'm looking at finishing up things and then I will deploy it. I am really looking forward to what you guys think.

**Comment by Gerben321** [comment]
@Konstantin-Levin @OleksiyRudenko This is now deployed. Let me know what you think!

**Comment by Konstantin-Levin** [comment]
This is great! A really nice improvement, thank you. Working well for me on Firefox desktop, just one tiny bug that I came across where the upper separator line disappears when clicking to show the dropdown for a particular component. 

<img width="1145" alt="Screenshot 2024-02-24 at 09 27 03" src="https://github.com/Gerben321/bike-care-tracker/assets/155573822/d7630e99-49a5-4bd6-96c8-db7e383bd46b">
<img width="1159" alt="Screenshot 2024-02-24 at 09 27 17" src="https://github.com/Gerben321/bike-care-tracker/assets/155573822/a2a1675a-cfb2-435a-8c51-a66b07648b8f">

The red and yellow icons indicating service status is useful importation to have at a glance, and it keeps the page looking clean.

As I mentioned in my earlier post I think it would be nice to have just one more line of text in the component drop down showing the km/hrs remaining (or overdue) until the service. This saves the 2 click throughs to _Details_ and then _Service_ to see that number.
This would also help when I want to quickly check the service info for 2 or more components one after the other.

**Comment by Gerben321** [comment]
Thanks for that, didn't notice that before! Will have a look at that.

I think that would be a good idea to add the remaining service.

**Comment by Gerben321** [comment]
Fixed the bug.

How would this work for you? 
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/b0f66510-2d17-4fa6-87ed-25b2599f441f)
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/fd6608af-2619-4183-8399-6994e3fa51d9)

You can also leave feedback on the looks, not just function. I want to make it look as good as possible while I'm at it.

**Comment by Konstantin-Levin** [comment]
Nice one, looks ideal  - you read my mind! 👌

The font colour to match the priority is a nice touch, helps it stand out. Only thing I'd say is check the legibility of the coloured text when on light mode. The yellow might be a little hard to make out?

<img width="392" alt="Screenshot 2024-02-24 at 20 12 33" src="https://github.com/Gerben321/bike-care-tracker/assets/155573822/7bffe701-03b9-4754-9e6a-1b5bc35238a7">


One more small thing that is totally a personal preference thing for me is showing 2 decimal places on everything measured kilometres. For example:

**13,409 km** just looks less fussy and quicker to glance at than **13,409.08 km**

I0s and 100s of metres (along with seconds in time) are not really relevant to me when tracking anything on my bikes 😅 but that's just me.

**Comment by Gerben321** [comment]
Good point about both! Will take a look at that tomorrow.

**Comment by Gerben321** [comment]
How about this?
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/f113edcb-ce41-4c3b-8482-92e247d39c6d)
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/2657a0fc-700a-4c90-9cce-f73a0427db23)

Turned it into an alert type of message so the text can be black or white depending on the color.

**Comment by Konstantin-Levin** [comment]
Nice 😎 That's even better, stands out really well now.
Just the right amount of info in that drop down now I think
