### ISSUE TITLE
Create app in appstore(s)

### ISSUE THREAD

**Issue by Gerben321** [Gerben321/bike-care-tracker#25]
In case you didn't know yet, Bike Care is already a PWA (Progressive Web App), meaning you can use things like push notifications, and pin or install (depending on your OS and browser) it almost like a real app.

I'd like to bridge that gap a little bit more, and introduce some more visibility and put Bike Care in at least the Google Play Store. The app will serve the PWA version of Bike Care and will not add features. It's simply to make it easier for people to use that are not familair with PWA's.

The Windows store should also be possible, albeit perhaps not the most interesting market. 

The Apple market would be nice, but I'm afraid that's going to be both expensive and difficult without any iDevices. In case there's an apple user willing to help me out with this (both financially or with testing), let me know!

**Comment by OleksiyRudenko** [comment]
I was wondering if there is a way to easily convert a PWA into an Android app. At the end of the day an app could be nothing more than a WebView serving web content.

Looks like it is possible since 2019 already.

Sharing some findings here for reference:
- https://medium.com/appmaker-xyz/how-to-convert-pwa-to-an-android-app-f06bac5d2e29 (also check the links therein)
- https://developer.chrome.com/docs/android/trusted-web-activity/quick-start

There must be a more up-to-date approach. Just didn't come across yet.

I can imagine that you may want to add no or slow connectivity issue to warn a user and/or cache data locally to offer at least read-only functionality (or probably deferred data upload) when no Internet available.

**Comment by Gerben321** [comment]
Yeah that would be cool! I was indeed looking at offline support aswell. Not sure how difficult that is.

I even saw I can add windows 11 widget support, although I'm now sure how beneficial that is.

As far as I know there'sq  a cli tool called Bubblewrap that is the tool for the job to convert a PWA into an app. So I'll play with that!

Thanks for the links.

**Comment by Gerben321** [comment]
I'm working on a WIP version on Android. In case anyone wants to try out it, can you send me your Google Account that you use on your Android phone? I can then add you to the internal testers before I publish it.

**Comment by Gerben321** [comment]
The link is now working @OleksiyRudenko. I'll try it out and see how it works.

**Comment by OleksiyRudenko** [comment]
@Gerben321 JFYI, the link above when followed says:
```
App not available
A testing version of this app hasn't been published yet or isn't available for this account.

If you've been invited to become a tester, make sure you're signed in to the account that was invited to the testing program. If you've been invited to a Google Group as part of the program, make sure you've joined the Group.
```

Probably, you'd need to invite testers. I'm willing to become a beta tester. I will PM you on Reddit and share my email address.

**Comment by Gerben321** [comment]
I've added you to the list, thought it was a public link. If others want to try, let me know.

I am aware there's currently something weird about the titlebar, the PWA applies a color to it, but for me it's just black no matter what I do on the app. I'll have to see what's that about.

**Comment by OleksiyRudenko** [comment]
@Gerben321 I have registered as a beta tester and have the beta app version installed.

**Comment by Gerben321** [comment]
Did you find anything weird? I don't think so right? Since it's basically the PWA (It's called a TWA if you're wondering in this case) but downloadable from the store. I'm going to publish it for everyone, see if we get some extra users.

**Comment by Gerben321** [comment]
I've made the app available for the public! I've added some nicer screenshots. Let's hope people find the app. I will add a link to the website soon.

https://play.google.com/store/apps/details?id=com.gerbenbol.bikecare.twa

**Comment by Gerben321** [comment]
@OleksiyRudenko Before I forget, you can (if you want) remove the beta version, and install the public version. And I would love to get a review!
