### ISSUE TITLE
Missing bike identification in service schedule view

### ISSUE THREAD

**Issue by OleksiyRudenko** [Gerben321/bike-care-tracker#26]
**Describe the bug**
Bike identification is not available/visible in specific service schedule view for an installed component.

**To Reproduce**
1. Go to https://bikecare.gerbenbol.com/dashboard/service-schedules
2. Click on Details of any service entry
3. Observe missing bike identification for an installed component (see screenshot)

**Expected behavior**
A bike identification is present and visible

**Screenshots**
![image](https://github.com/Gerben321/bike-care-tracker/assets/8686631/d88dd99d-7434-47c1-a107-0d801b5fea05)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 121

**Smartphone (please complete the following information):**
 - Device: n/a
 - OS: n/a
 - Browser n/a
 - Version n/a

**Additional context**
n/a

**Comment by Gerben321** [comment]
Thanks for the detailed issue! That should indeed be there. I'll have a look.

**Comment by OleksiyRudenko** [comment]
On a second thought, it also would be nice to know (see) what is the type of component. In this particular case I have a Kenda tyre (actually two of them :) ) but from this view I cannot tell if it is a front or rear wheel.

**Comment by Gerben321** [comment]
Yeah that would be useful. I think the whole visual of this card needs to be uncluttered so if you think something can be removed or moved let me know.

**Comment by OleksiyRudenko** [comment]
Yeah, probably worth revamping when you are going to touch the component at all.
Here is the proposal for the text block before the ring chart with some heavily opinionated explanations.

(I am sorry, I cannot confidently suggest any proper Dutch translations)

Mockup / example:

**Tyres check**
🚲 **[Bike Name](fake-link)**
Front wheel: **[Kenda tyre 26x2.1](fake-link)**
Distance to service: **1,760 km** (_imagine it is of green color :-)_ )
Distance done: **39.53 km**
Service frequency: **1,800 km** of **Total distance**
Last service: **N/A**

Comments:

- **Tyres check** // Service title. No change.
- **🚲 [BikeName](fake-link)** - Link leads to the bike view page
- **Component type: [Component make and model](fake-link)** - Link leads to the component view page
- **Distance to service: 1,760.47 km** - Was "Service distance left". Keep it color-coded - really helpful. This item bubbled up as it is a more critical piece of information to know than those below here. Do we actually need accuracy to tens of meters? Rounded to full kms or miles should work well enough.
- **Distance done: 39.53 km** - No change. Maybe round to full kms / miles
- **Service frequency: 1,800 km of Total distance** - Was "Scheduled distance:..." and "Type: total distance"; now combined as a single entry; comes after service to distance as it gives rough understanding of a scale (total vs remaining)
- **Last service: N/A** - the least critical piece of information

**Comment by Gerben321** [comment]
Turns out the bike make and model are used to display the name there. This will be changed to the big 'nickname' used in other places. I'll have a look at your ideas to improve the display of the rest now.

**Comment by Gerben321** [comment]
This is what I've changed so far:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/04f5a416-a68b-485d-8b0c-91caba16ec1a)
I've followed most of your feedback I believe. Let me know if I've missed something or change something else.
The ring is now also inverted. Because the text in the center is 'x left' I found it more logical that the bar would also show how much is left, instead of how much is done. What do you think?

**Comment by Gerben321** [comment]
Deployed right now.
