### ISSUE TITLE
Add component type whenever a specific component custom title is shown 

### ISSUE THREAD

**Issue by OleksiyRudenko** [Gerben321/bike-care-tracker#28]
**Is your feature request related to a problem? Please describe.**
I want to know what I am about to oil or which wheel (front or rear) to check.

**Describe the solution you'd like**
It would be great to have component type specified (chain and front wheel in my case; see screenshot for ref).
I guess it is important to know the component type in every view a specific component is shown.

**Describe alternatives you've considered**
1. Remembering what I meant.
2. Add keywords in component custom title, effectively doubling the component type picked from the predefined list.

**Additional context**
![image](https://github.com/Gerben321/bike-care-tracker/assets/8686631/98ba3eb6-1b41-435f-9d60-e15f6e900196)

**Comment by Gerben321** [comment]
Sounds good. My only thought is the space available in case of either a long component name or component type. The table can look weird then, or info might be cut off.

I can either do
- component type - component name
- component name (component type)

The first one is what I've added in the bike details page and is the most consistent, but might cut off data from the component name. I'll have a try and you can see if it looks good.

Maybe I can get rid of the ID column in all places as well for extra space. That's a bit of a habit as a developer. Not sure if that adds anything for normal poeple 😜

**Comment by OleksiyRudenko** [comment]
How about a column for component type?
Pros:
- table become sortable by component type
- long component types could be shortened (sacrificed) on mobile independently of component name

> Maybe I can get rid of the ID column in all places as well for extra space. That's a bit of a habit as a developer. Not sure if that adds anything for normal poeple 😜

Yes, please :-D

Also,
- Next service - round to full kms / miles
- "Details" => Icon (✏️)
- "Distance interval", "Total distance" => icons. Not suggesting any as it would probably make sense to resolve this for all service types consistently.

I could think of the following icon ideas for the two above:
- Total distance: `|==>|`
- Distance interval: `=>|=>|`

**Comment by Gerben321** [comment]
Another idea would be to give the whole row a (not too bright) color. But that might look like a circus with a lot of schedules. 🤔
> "Details" => Icon (✏️) and no need in column name.

I can also make the title of the schedule a link? Not sure how 'logical' that is.

> Status - make color-coded icons

I think this would be good. Might not save space, but easier/quicker to see at a glance. May even as first column.

> "Distance interval", "Total distance" => icons.

Not convinced how clear that would be for new people. Now that I think about it, how much does the type of schedule add here? Maybe all you need to know is how much distance of time is left, not whether it's an interval or total distance left. When you go to the detail page you can see everything about it.

**Comment by Gerben321** [comment]
This is what I've made so far:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/f375ef64-a9fa-4fd1-b2dc-a44df2ebf761)

**Comment by OleksiyRudenko** [comment]
> Another idea would be to give the whole row a (not too bright) color. But that might look like a circus with a lot of schedules. 🤔
I agree, that would be too much.

> I can also make the title of the schedule a link? Not sure how 'logical' that is.

Makes sense as long as it leads to a specific component schedule details. Not critical tho, IMHO.
However I like when everything is connected even if covers only corner cases.
![image](https://github.com/Gerben321/bike-care-tracker/assets/8686631/a1e8568f-5936-4056-b4f6-3176da39b00d)

> > "Distance interval", "Total distance" => icons.
> Not convinced how clear that would be for new people. 

Agreed. Non-commonly used icon may confuse.

> Now that I think about it, how much does the type of schedule add here? Maybe all you need to know is how much distance of time is left, not whether it's an interval or total distance left. When you go to the detail page you can see everything about it.

I'd keep it. Imagine, I have 2 chain-related schedules. Even if I fail to set desciptive schedule title, type of schedule can give me a quick idea on what I am supposed to do - replace the chain or just oil it. It can be a bit overcommunication in this view but will save me a click and page load to double-check (it is still important as slightest delays with even not-so-often lagging optic cable connections are annoying).

**Comment by OleksiyRudenko** [comment]
> This is what I've made so far: 
Looks clean and informative 👍 

I would just change the red icon to something "saying" more about the danger than... 

This particular red icon ![image](https://github.com/Gerben321/bike-care-tracker/assets/8686631/6409f322-84fd-4d89-9dbe-e787c169d5b2) looks a bit confusing to me, more like the "close the window" or "close the notification" control on MacOS. It could be my bias and I realize that what I proposed above has been quite a lazy choice (quickly picked emojis) and is less appropriate. But I would stick to something more prominent and screaming about danger.
Altough not crtitical.

Just an example for inspiration:

![image](https://github.com/Gerben321/bike-care-tracker/assets/8686631/bccee89d-6199-457c-ba2f-476beb07e9c6)

Or even octagonal shape, distinctive from the web accessibility standpoint. You will have round (soft and nice) green, yellow triangle warning, and red octagonal. Just like "STOP" signs on the road are octagonal and you recognize it immediately among any other road signs.

<a href="https://previews.123rf.com/images/igor170806/igor1708061707/igor170806170700118/81917172-warning-red-octagonal-sign-with-exclamation-mark-for-prohibited-activities.jpg"><img src="https://previews.123rf.com/images/igor170806/igor1708061707/igor170806170700118/81917172-warning-red-octagonal-sign-with-exclamation-mark-for-prohibited-activities.jpg" width="120" /></a>

Still, not critical. Feel free ignoring. It is most likely just me being overly pedantic.

**Comment by Gerben321** [comment]
Thanks. Good points about the icons. I'll see which one would suit.

About the component type in the table. Would a separate column work best, or combine the component type and name?

The link would indeed go to the schedule details. I'll work on a new version for you to check. You seem to know a lot about these things so I'd like to use your expertise if that's okay!

**Comment by Gerben321** [comment]
Here's a new version:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/7f40b865-f14a-41ca-be7a-6f34d468d20b)
The icon looks a lot better indeed! I've removed the details column and moved that link to the title.  The type is back, and I've combined the component name and type. What do you think?

**Comment by OleksiyRudenko** [comment]
> About the component type in the table. Would a separate column work best, or combine the component type and name?

I'd put a column. This way component names would be nicely aligned along common vertical (imaginary) line. And both columns (type and name) would be sortable independently that offers greater flexibility UX-wise.

> The link would indeed go to the schedule details. I'll work on a new version for you to check. You seem to know a lot about these things so I'd like to use your expertise if that's okay!

Not an expert tho. Just a really pedantic user and had a privilege to observe true UX designers working on succesful commercial projects. I am more than happy to help. You are developing a helpful project and dedicated to it. Given it is available for free, it's the least I could do for your project.  You are also quite responsive and willing to listen to the users even when there quite a few of active ones. Lots of respect.

**Comment by OleksiyRudenko** [comment]
> I've combined the component name and type. What do you think?

Looks nice in this specific setup. Not sure if component type will be significantly longer. It may disrupt visual harmony. But let's see.

**Comment by Gerben321** [comment]
A column for the component type would look like this:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/83eb91ad-0cc4-4ebf-b27c-eedcf3f2c69c)
I get the pro's and cons of them both. I'm fine with both in this case.
