### ISSUE TITLE
Add notification(s) when schedule is (over)due

### ISSUE THREAD

**Issue by Gerben321** [Gerben321/bike-care-tracker#3]
Add a notification, either push or email or something else when a schedule is almost due, or overdue. The almost due should be a setting on the schedule.

**Comment by Gerben321** [comment]
I've started on a notification setup yesterday. On the dashboard you should already see a button where you can enable push notifications. Right now that should work without errors (let me know if you get errors popping up), but nothing happens right now. No notifications are sent yet.

The plan is to add control over what type of notifications you should receive.

For now there are 2 type of channels you can receiver notifications over; web push and email. I'll have to add a way to enter your email in your account as I can't get that from Strava.

The current options are notifications for when an activity is added or updated from Strava. These will not be enabled by default because they don't add much IMO, and are more 'debuggy' kind of notifications. The major one for now is to get a notification when a schedule is overdue. Will have to build some kind of system that keeps track of when a previous notification was sent, because it's not ideal to receive a notification about that every time you finish a bike ride.

**Comment by Gerben321** [comment]
If you visit https://bikecare.gerbenbol.com/dashboard/user/settings you can enable/disable whatever you want. There are no emails sent right now, but you can change the settings in advance.

More types of notifications can be added later. Let me know if it doesn't work properly or if you have suggestions.

**Comment by OleksiyRudenko** [comment]
@Gerben321 thank you for adding notifications and their management.

> @OleksiyRudenko Do you maybe have suggestions or ideas regarding this?

I reckon the practical use will show what would be appropriate to add/change.
