### ISSUE TITLE
Service log entry default values

### ISSUE THREAD

**Issue by OleksiyRudenko** [Gerben321/bike-care-tracker#33]
**Is your feature request related to a problem? Please describe.**
I want my service log entries be consistent.

**Describe the solution you'd like**
When on service log entry view https://bikecare.gerbenbol.com/dashboard/component/4/service-log/add 
![image](https://github.com/Gerben321/bike-care-tracker/assets/8686631/f53ce4b3-ff19-4b52-a68e-37bc3319e581)
I want service title and mileage be pre-filled with defaults.

Title would be: `<Component type>` `<Component name>` - `<Service schedule title>` `<Service frequency>`
Mileage: latest known (currently it is exposed to the user but the input field is not pre-filled).

This feature will enable #32 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

P.S. Please feel free asking me to stop bursting with ideas :-) I am also completely OK if you drop any of those or let them stale.

**Comment by Gerben321** [comment]
I think the interval might be a bit much in the title, but the rest seems logical. Is that good for you or do you think the interval adds a lot of value?

Btw: Your ideas are great so far!

**Comment by OleksiyRudenko** [comment]
Internal is not critical. I could just miss it, but guess it is available on the schedules log list view. That would be sufficient.

Please drop interval from the wishlist to this feature. Sometimes I overthink and overcomplicate things. It is always good to have a second pair of eyes and opinion.

**Comment by Gerben321** [comment]
This is now added. Can you test it and let me know if it's good?

**Comment by Gerben321** [comment]
I'll close this for now. Feel free to open a discussion or new issue in case it needs improvement.
