### ISSUE TITLE
Service urgency/criticality visualization is not consistent across the app

### ISSUE THREAD

**Issue by OleksiyRudenko** [Gerben321/bike-care-tracker#37]
**Describe the bug**
The app draws attention to a service due soon...
... on the dashboard
<img width="734" alt="image" src="https://github.com/Gerben321/bike-care-tracker/assets/8686631/72cbd7c2-2903-4996-af0c-4a36b16125f5">
... and in the bikes list
<img width="258" alt="image" src="https://github.com/Gerben321/bike-care-tracker/assets/8686631/50def8b6-cff2-435d-887a-73c9bdd81a01">

But not on the schedule list.
<img width="967" alt="image" src="https://github.com/Gerben321/bike-care-tracker/assets/8686631/65f5a5ff-edaa-4855-973b-bfe4d5b4eae0">

**To Reproduce**
1. Go to https://bikecare.gerbenbol.com/dashboard/service-schedules
2. See incosistent status icon when the service is due soon or overdue

**Expected behavior**
The service status icon is either yellow or red when the service is due soon or overdue.

**Screenshots**
See as embedded above.

**Desktop (please complete the following information):**
 - OS: MacOS 14.3
 - Browser Chrome
 - Version 121.0.6167.85 (Official Build) (x86_64)

**Smartphone (please complete the following information):**
 - Device: OnePLus 8T
 - OS: Android 13
 - Browser Chrome
 - Version Latest as of 2024-02-20

**Additional context**
n/a

**Comment by Gerben321** [comment]
Good find. There's indeed a bit of a difference there. The table only shows overdue, and the other places show almost or overdue.

Indeed a third color would be good. Green for good, yellow for maybe 15% left, and red for overdue? On the pie chart there is green and yellow and orange and red. But that might be overkill for other places. 

What do you think? That way I can apply that everywhere.

**Comment by OleksiyRudenko** [comment]
To me, yellow (with whatever rule you currently have already got in place) for the nearing service and red for overdue would work perfectly fine.

Orange might be good on service with longer utilization period, like chain or cassette replacements (when 15% with yellow is rather early heads-up). Would be nice to predict 1 day due. I.e. in this scenario yellow would stand for "buy a replacement", and orange "be ready to replace in a day or two".

**Comment by Gerben321** [comment]
This is my proposal:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/06fb3251-ac2c-4237-aa66-68e8fd9f0e27)
- 0% left = red.
- 15% or less = orange
- Above 15 = green

**Comment by Gerben321** [comment]
I've deployed this update, let me know what you think. Feel free to drop a comment if the percentages need some work or if you still found something that's inconsistent!
