### ISSUE TITLE
Enable mobile home screen shortcut

### ISSUE THREAD

**Issue by OleksiyRudenko** [Gerben321/bike-care-tracker#4]
**Context**
Android allows adding a shortcut to a webpage to the home screen from browser (three-dot control => Add to Home screen). This helps to group web bookmarks with native apps (e.g. along with Strava app).

**Proposal**
Change web page title from "Welcome!" to "BikeCare" for better bookmark identification.

Current behavior:
<img width="300" src="https://github.com/Gerben321/bike-care-tracker/assets/8686631/0d58d6be-1c35-424f-9bd3-f5c7e82f0bc3" />  <img width="300" src="https://github.com/Gerben321/bike-care-tracker/assets/8686631/a960bb9f-f44f-47bb-af1d-8114ee8f0c75" />

Desired behavior:
<img width="300" src="https://github.com/Gerben321/bike-care-tracker/assets/8686631/5358e828-0ec2-4624-86d7-691f30fdbdbc" />

P.S. You may want to consider adding PWA capabilities. Given the web app is responsive should be a relatively easy task.

**Comment by Gerben321** [comment]
Thanks that's a good idea. Will put it on the list.

**Comment by Gerben321** [comment]
@OleksiyRudenko  I've added some icons and created a manifest.json file to give it basic PWA capabilities. You should be able to try it out now.

**Comment by Gerben321** [comment]
Seems like I can't get the shortcuts to work on Android right now, but seems to work nice on Windows 11 with Edge.
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/d54428aa-46d7-4de6-adb4-d8ddc24f2d32)

**Comment by OleksiyRudenko** [comment]
@Gerben321 Now Android Chrome offers `Install Bike Care` instead of `Add to Home Screen`.
From this point on the experience is exactly the same as with any other Android app.
Great improvement!

If you manage to find a way to initialize installation right from the web page, the overall experience will be super-native-like 👍

Similar experience on Win 10 / Chrome. The app appears among other app in the system drawer and on the taskbar 👍 

![image](https://github.com/Gerben321/bike-care-tracker/assets/8686631/21c0536d-e9fe-4922-9f01-539cc15adb61)

![image](https://github.com/Gerben321/bike-care-tracker/assets/8686631/8b0e8af8-03c4-40f2-aa97-1fee8f0a41f8)



Seemingly small improvement, yet a big leap towards app accessibility.

Please consider adding installation instructions somewhere on the app to help users have it exactly where they want to find mobile/desktop apps.

**Comment by OleksiyRudenko** [comment]
Sorry for not being able to test iOS experience due to having no an iPhone.

**Comment by Gerben321** [comment]
So you mean like a button on the page itself? If that's what you mean I'm not sure that's possible, but instructions how to do it should be possible for sure!

I don't have an iPhone myself but I could try to see what happens on my gf her iPad. Hopefully that's a similar experience.

**Comment by Gerben321** [comment]
Just tested on an iPad. It's not as fancy as on Android and Windows (surprise 😊), but it's a basic bookmark, but with the icon working. So fine with me. I'll close this as I think this is completed. A new issue can be opened for extra features on this.
