### ISSUE TITLE
Add installation date while creating component

### ISSUE THREAD

**Issue by Gerben321** [Gerben321/bike-care-tracker#42]
I think it would be nice and efficient if we can add the installation date (usage period) when adding a component to a bike. I think a simple checkbox (defaults to off?) would work fine. When the checkbox is selected extra fields would come in screen where you can add the installation date.

**Comment by Konstantin-Levin** [comment]
Good idea, adding the usage period is a bit clunky at the moment. Would be nice to do it all from the same page

**Comment by Gerben321** [comment]
Do you mean the overall management of periods? Or the adding. Because I'd love to streamline the overall process if possible.

Maybe buttons to quickly install or remove the component? Not sure how that should work if you would 'remove' a component a day or two later than you actually removed it.

Maybe a button with remove and install (depending on the current state) and then a popup with the option to select 'now' or a specific date.

Just thinking out loud. 🤔

**Comment by Konstantin-Levin** [comment]
I meant when adding a new component to a bike, your suggestion is good I think
> I think it would be nice and efficient if we can add the installation date (usage period) when adding a component to a bike. I think a simple checkbox (defaults to off?) would work fine. When the checkbox is selected extra fields would come in screen where you can add the installation date.


But also, regarding adding a usage period. I think the boxes where you select date and time could be smaller (on desktop browser version). Is there any need for them to be so long?
<img width="1150" alt="Screenshot 2024-02-25 at 18 01 13" src="https://github.com/Gerben321/bike-care-tracker/assets/155573822/fe4577ec-98b3-4e12-9a48-c13b7970a21c">

**Comment by Gerben321** [comment]
Would this work for you?
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/6a68fcfd-1c16-46e2-b294-2f0143733d44)
This is 100% the native date time field from the browser. You can click the calendar icon to set both the date and time. Or are the separate fields better?

**Comment by Konstantin-Levin** [comment]
I think keep separate fields for date and time, but time could be in one field (rather than the current version which has hh:mm as separate fields)

I would also prefer to keep the ability to input date and time manually via the keyboard as this can be sometimes quicker than using the calendar pop out.

As mentioned in #9 I think a default figure for **start** time should still be filled in automatically. I think in the majority of cases the time a component is installed is not important to the user, and would be an annoying extra step 
(but still necessary to have in situations where, for example, the user records a ride and carries out a service on their bike on the same day)

**Comment by Gerben321** [comment]
The time is still possible to enter with the keyboard, but having it as a separate field is fine as well. I'll have to check if using two fields (date and time) is possible with the framework I'm working with. Otherwise I'll leave it as is for now with a bit better styling.

**Comment by Konstantin-Levin** [comment]
👍 not a problem either way really. Just trying to think of ways to keep things efficient as possible when a new user is adding many components in one go (as I did when first using the app)

**Comment by Gerben321** [comment]
Got some progress. When adding a component you can now check this box:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/19f25593-c461-4776-be72-ef607ae5d703)
In here you can enter the period. I'm not sure about the end date here, because the question is about if it's installed, but it might be something that WAS installed.

![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/d664220f-d86d-4fed-b686-230a386bff14)

What do you think about both dates @Konstantin-Levin ? Maybe rename the checkbox? Or is it fine now.

Anyway, I think this really improves the flow of creating components.

**Comment by Konstantin-Levin** [comment]
I agree a user may want to add a component that is not currently installed (I definitely did this). Maybe you should stick with _'Add usage period'_ or similar for the checkbox then there is no contradiction in language? 

Related: should the wording of _Installation date_ and _Removal date_ match that of the add/edit usage period page?

<img width="1152" alt="Screenshot 2024-02-29 at 22 21 02" src="https://github.com/Gerben321/bike-care-tracker/assets/155573822/4117092e-5736-43d5-897b-e96547805379">

**Comment by Konstantin-Levin** [comment]
This got me thinking: Is there a way to make it more obvious to the user that it is not necessary to fill in any data for the Removal date/End date if the component is currently installed and active?

Maybe just me or is there potential for confusion that something _needs_ to be entered here?

Perhaps have it greyed out initially with a check box to activate, or a small line of text to explain that it can be left blank?
Just a thought - might not be required.

**Comment by Gerben321** [comment]
I was actually thinking of renaming the whole 'period' and their start and their end date. For me after some thought, an installation date and optional removal date sound better/make more sense. What do you think? Maybe rename periods to installations.

And yeah, the end date/removal date should be clearer that it's optional. What I came up with for now is this text above the input: `Removal date (leave empty if currently installed)`. I hope that it's clear enough that way.

**Comment by Konstantin-Levin** [comment]
I agree, I think you could change 'Start date' to 'Installation date' and 'End date' to 'Removal date'
>Maybe rename periods to installations.

Hmm, this is a tricky one. Just the word Installations isn't quite right I don’t think as it implies Removals should be separate. I would say just stick to periods - it's not perfect, but easily understandable I think.


> Removal date (leave empty if currently installed)

👍 Yes I think this works fine 

>should you be able to add multiple usage periods at once?

I think your instinct is right, it might be too complex for a new user. I would leave it as it is. Entering multiple usage periods is still pretty quick at the moment.

And going back to this screen each time reinforces to the user that the period they just entered is correct:
<img width="1096" alt="Screenshot 2024-03-01 at 19 20 46" src="https://github.com/Gerben321/bike-care-tracker/assets/155573822/926229ce-477c-4da0-86e1-9754ba15e49b">

**Comment by Gerben321** [comment]
Thanks for the feedback! Good to hear I'm on the right track.

Yeah I also noticed it's a little annoying you don't return to the overview of periods after adding or editing one. I was planning to make that a separate link which you return to. The 3 pages for the component (edit, schedules, periods) will get a separate link and editing on one of the pages will return to that overview back.

**Comment by Gerben321** [comment]
I've deployed this now.
