### ISSUE TITLE
Consitency in displaying of distance and time measurements

### ISSUE THREAD

**Issue by Konstantin-Levin** [Gerben321/bike-care-tracker#44]
As mentioned in #23 maybe you should decide how you want to display distance and time across the whole app for a consistent look?

>13,409 km just looks less fussy and quicker to glance at than 13,409.08 km
I0s and 100s of metres (along with seconds in time) are not really relevant to me when tracking anything on my bikes 😅 but that's just me.

**Comment by Gerben321** [comment]
Good point. Maybe we should go towards dropping the double digit precision. If people really want it, I can always make it an option.

**Comment by Gerben321** [comment]
Right now my plan is to show one digit after the comma/point, except for on the service schedule pages. I personally find 23,6km on a ride informative.

If it's really not prefered to have it like that, I will have to make it a setting.

**Comment by Konstantin-Levin** [comment]
Good point. I agree with all of that 👍 
I don’t think an extra setting is required, unless a lot of users request it I guess.

**Comment by Gerben321** [comment]
It's now released. Let me know if it's better.
