### ISSUE TITLE
Elevation figures from weekly/monthly/yearly statistics pages typo/inconsistency 

### ISSUE THREAD

**Issue by Konstantin-Levin** [Gerben321/bike-care-tracker#52]
<img width="1193" alt="Screenshot 2024-03-04 at 21 32 21" src="https://github.com/Gerben321/bike-care-tracker/assets/155573822/4e2e1cd4-f0a6-4249-b43b-12ef0c934262">

Should the elevation figure be followed by the word 'meters' rather than 'meter'?

Or to simplify things just the letter 'm' (e.g. 986m) to match with the 'km' abbreviation for kilometres 
This also avoids spelling differences between UK and US English (metre vs meter) 

When using the Miles and feet unit setting this is shown correctly, I think, as:

<img width="1196" alt="Screenshot 2024-03-04 at 21 43 34" src="https://github.com/Gerben321/bike-care-tracker/assets/155573822/367d9c4b-d0a2-414e-b3cd-ec01a5c42b64">

**Comment by Gerben321** [comment]
Ah yeah good one. Never paid much attention to that. Great attention to detail. Will fix that in the next version. 👍

**Comment by Gerben321** [comment]
Fixed for next release somewhere today or tomorrow hopefully.
