### ISSUE TITLE
Add autocomplete field for component dropdown at service schedule add/edit page

### ISSUE THREAD

**Issue by Gerben321** [Gerben321/bike-care-tracker#55]
Right now the list of components for adding/editing a service schedule can get quite large if you really add all your components to a bike. This means you sometimes need to scroll and search for the part. It would help a lot I think to have an autocomplete field there like in other places.

**Comment by Konstantin-Levin** [comment]
This autocomplete field does not work for me at the moment and returns 'No results found' for all text entry? This is on mobile and desktop

**Comment by Gerben321** [comment]
Can you try to refresh your cache? Have you selected a bike that has components? Should work then. Otherwise we have to debug it.

**Comment by Konstantin-Levin** [comment]
Ah yes, my mistake. 

I had thought when, for example, I searched for 'handlebar' on a bike for which I haven't added one that it would display something like _Handlebar: no component found_ rather than just _No results found_

Just me being stupid

**Comment by Gerben321** [comment]
Good to hear it's working! Just FYI, the component type like a chain is combined with the name of the component. So you can't see the component type with or without the corresponding component.

I could check if the message for no results can be changed to the subject, so for this case components.
