### ISSUE TITLE
Improve design and data on bike component details 

### ISSUE THREAD

**Issue by Gerben321** [Gerben321/bike-care-tracker#59]
I think the new list of bike components is great, especially with the filtering. However there are some nice improvements that can be done. First of all I think the list items, once dropped down, don't look that great.

Here's what I imagine could improve it:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/ca3fab59-16f8-4c09-a699-a775d16c891b)
The name of the component is gone in the details because it's already in the list. The distance and moving time are now moved into a 'stats' kind of display like you can find in other places.

An addition is the service status. This is displayed like with the orange and red icons in the overview if something is (almost) overdue. This however also shows a green checkmark if it's good (like in the service overview table page).

I'm still thinking how I can improve the two buttons to edit and remove a component. It doesn't really look right, not sure why.

I also think this might be a good place to try to convince the user to create a service schedule for this component. Right now this is what I have in mind:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/ccfc5d12-dcd6-42a5-8c3a-13a935670bb3)
Maybe some text explaining how there's no service schedule so you can't track the status with a link to create one would make it easier to convince the user to create one.

What do you think so far?

**Comment by Konstantin-Levin** [comment]
New look is a big improvement for sure 👍

The last image that shows all the information within the card looks best I think. Nice & clean.
Could the service status card contain the remaining km/hrs etc even if not overdue.

e.g.

Service status
Good: <521km 

Service status
Almost due: <10km 

Service status
Overdue: >47km

(or similar?)

Maybe clicking on the text in the service status card could link to the specific service schedule page you mention?
& if no service schedule has been added, clicking on _N/A_ would take you to the page to add one?

Just random ideas...

**Comment by Konstantin-Levin** [comment]
> I'm still thinking how I can improve the two buttons to edit and remove a component. It doesn't really look right, not sure why.

Maybe separate the buttons slightly and give them each their own box? 
Play around with a different font maybe?

**Comment by Gerben321** [comment]
Here is a small update for the status cards:

Good:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/d208a329-c2bb-4450-850d-472c930c93f2)

Unknown:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/c6af051e-49d8-4686-b398-1b0c5b4d94df)

Overdue:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/43ab74c4-6f72-456c-b98b-fd84488f24c0)

Almost:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/8de32fb3-9c43-497e-a2f5-3549375c835c)

**Comment by Gerben321** [comment]
For the part below I still have to think about what to do with it... Maybe leave that for later when I get some creative ideas.

**Comment by Gerben321** [comment]
I will now deploy a new version with the current progress of this feature. @Konstantin-Levin Can you check it out and let me know what I think? I will leave it open in case you can think of other things, or when I find some more inspiration.

**Comment by Konstantin-Levin** [comment]
Looks good overall. If I'm being picky I would say some of the text is redundant and could be removed:

<img width="1138" alt="Screenshot 2024-03-18 at 22 07 56" src="https://github.com/Gerben321/bike-care-tracker/assets/155573822/44e969f9-b4dd-4420-bfb0-20c7d016560c">

I don’t think 'almost overdue service' is necessary as it is already shown in the card and obvious because of the yellow icon.

Similarly:

<img width="1137" alt="Screenshot 2024-03-18 at 22 07 48" src="https://github.com/Gerben321/bike-care-tracker/assets/155573822/053c32e4-5b88-4dc4-ad04-a7c7ebc179dd">
 
I don’t think 'overdue' in the red text is necessary. Just _-17km_ in red makes it obvious (along with 'overdue' in small font below.  

New component action buttons look better 👍

**Comment by Gerben321** [comment]
I get what you mean. The title for the text is indeed a bit redudentent. However I want to show the text about the overdue service and without the title it doesn't really stand out I think. But I could make it more generic like 'service information'.

I also would like to add a text in case there is no service schedule at all. That way users might get triggered to create a schedule for that component.

Thinking about that. Would it help the more basis user to show random examples of schedules? General ones or linked to a type of component? To make it easier for them. That's a bit off topic and more complex then it sounds though. 😅

**Comment by Gerben321** [comment]
I've removed the 'overdue' text in the -17km example from you.

Do you have a good idea how to link to the specific overdue schedule? I think it's good to link to the overdue schedule when there is one.

**Comment by Konstantin-Levin** [comment]
Could you include it as a third option in the component actions box and link from there? You could have that for every component regardless of the service status. 

It could just say _Service schedule_ or _View/create service schedule_ 

Might help nudge users to create a service schedule when they haven't already?

You could then remove this text entirely perhaps?: 
_Overdue service
For more information about this service schedule please click here._

**Comment by Gerben321** [comment]
How about this?

State for no service schedule:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/0ae628d4-f94d-4a40-8172-22030ff4babd)

State for overdue schedule:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/812e6446-78cf-45be-94a5-31cd17af22b6)

The almost overdue is really similar to it:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/db478651-3585-427c-8614-4cd2c1257ff8)

And to make it complete a good schedule:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/4775c1de-26aa-4932-af93-625ad02f8832)

I like the list of actions personally. Not per se visually, but functionally. This is a good way in the direction of plenty information without cluttering, but giving important information. And the 'Add service schedule' button is really fast and useful IMO already.

**Comment by Gerben321** [comment]
I'll deploy this right now as well. Play around with it and let me know what you think. This is certainly going in the right direction I feel!

**Comment by Konstantin-Levin** [comment]
Very nice - I like it! Seems to be working well for me so far 👏 

Looks clean and simple to understand/navigate. 

On a good schedule:

![image](https://github.com/Gerben321/bike-care-tracker/assets/155573822/37351d61-216c-4e7a-9b24-5597d894c94f)

I see the list of actions does not contain a link to _View service schedule_ as with the others. The implication of this made me realise that multiple service schedules can be added to a single component. Still learning!

**Comment by Gerben321** [comment]
Yeah that's done on purpose, sort of. The goal behind the link when service is (almost) overdue is to act on it. That's not needed when there's no urgence.

Should I change that button to a general button linking to the schedule overview for the specific component? So you can see them all, and you see the one with urgence there? Instead of a direct link when there is urgence? If that makes sense.

**Comment by Konstantin-Levin** [comment]
>Should I change that button to a general button linking to the schedule overview for the specific component? So you can see them all, and you see the one with urgence there? Instead of a direct link when there is urgence? If that makes sense.

Yeah I know what you mean - that's a good idea. Every component would then have 4 options from the actions box which keeps things looking neat

**Comment by Gerben321** [comment]
I've added the default link to the schedules page for all components now. Let me know if it's good now.

**Comment by Konstantin-Levin** [comment]
Looking good & working fine for me 👍
