### ISSUE TITLE
Activities page on mobile view could show activity name

### ISSUE THREAD

**Issue by Konstantin-Levin** [Gerben321/bike-care-tracker#61]
Perhaps it would be better to display the activity name alongside the 'Type' to make it easier to find a particular activity when scrolling through the list.  

![IMG_8021](https://github.com/Gerben321/bike-care-tracker/assets/155573822/c6eb0bf7-257e-49a7-aad2-d846196c738a)

Obviously you don’t want to make it look too complicated and some activity names will be too long to display in full - but there is some space remaining to show the name at least? 
Still worth retaining the drop down view to show all the extra info.

Not an issue on desktop clearly. Let me know what you think.

**Comment by Gerben321** [comment]
That's not what I had in mind for sure. The name should always be displayed and the type is far less important. It's a bit dynamic so weird stuff like this sometimes happen. But I will make it so the name is always visible.

**Comment by Konstantin-Levin** [comment]
Yeah that's looking good on mobile now. My Zwift rides have a really long name by default and it is cutting off with ellipsis now as expected.

Another quick thought occurred to me: maybe push the ride data to the right a little to make better use of the space?

![IMG_8024](https://github.com/Gerben321/bike-care-tracker/assets/155573822/795b27cb-74aa-402e-be01-9a965f78c40a)
 

(Sorry if I'm being too fussy, I'll stop if you like 😂)

**Comment by Gerben321** [comment]
Yeah that's something I need to do aswell, looks a bit weird.

**Comment by Gerben321** [comment]
This should be fixed in the release I did yesterday btw.
