### ISSUE TITLE
Active/Inactive vs Mounted/Unmounted vs Usable/Retired component 

### ISSUE THREAD

**Issue by OleksiyRudenko** [Gerben321/bike-care-tracker#64]
**Is your feature request related to a problem? Please describe.**
A component's Active property sounds ambiguous.
It would be great to have more explicit and specific properties names.
E.g. Mounted (meaning it is mounted on a bike), Retired (if a component is decomissioned and no longer would be mounted or serviced, kept on record for history backtracking purposes and for data consistency reasons).

**Describe the solution you'd like**
Change component property names to more specific.

**Describe alternatives you've considered**
Remembering the property meaning and deducing it by changing the value and figure the consequences out.

**Comment by Gerben321** [comment]
Yeah, like we discussed this is a good idea. What would be the best terms?

When a component is still good to use, but is installed on your bike, or not:
- Mounted/Not mounted or Unmounted
- Installed/Not installed or Uninstalled
- Active/Not active or Inactive

And when a component is no longer used, and will not be used anymore (broken, worn, etc):
- Decommissioned
- Retired

@Konstantin-Levin  Could you also help us think about this? This might be useful for you as well, since you're using a lot more bikes and components then we are, I think. 😎

**Comment by OleksiyRudenko** [comment]
Thank you for looking into this.
I have also added a couple more feature requests to deal with mounting and swapping components.

My rationale behind the term "Retired" was Strava's term. If BikeCare used the same term users will have proper mental connection between actions in Strava and in BikeCare.

Screenshot from Strava:
![image](https://github.com/Gerben321/bike-care-tracker/assets/8686631/02d885ec-abd8-4930-98ea-c90e5a3251ae)

**Comment by Gerben321** [comment]
I agree with that. That would sound good to keep the same term. And the placement in your screenshot also sounds good.

**Comment by Konstantin-Levin** [comment]
I agree with all of the above regarding the wording. I think each component could fall into 1 of 3 states.

1. Mounted
2. Unmounted
3. Retired 

I've got a few other ideas about retiring components. I'll put them in #65 as it seems the better place

**Comment by Gerben321** [comment]
I've just deployed a new version which got rid of the active toggle. It has changed to retired, which is off by default.

The rest is still the same, just changed same naming. Next up will be the mounted or not mounted display.

**Comment by Gerben321** [comment]
Here's a simple example of how it will look like:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/718c9209-36ea-477f-8756-c67af8bfd6e9)
The last install period is fetched, and the frontend will 'calculate' whether it's installed or not. It will then put it in the correct list and show it. I think I will also add a filter for this.

**Comment by Gerben321** [comment]
This is also deployed now. Let me know what you think 👍.
