### ISSUE TITLE
Service schedule based on time

### ISSUE THREAD

**Issue by Gerben321** [Gerben321/bike-care-tracker#7]
Ability to make service schedule trigger over elapsed time, not just riding time (e.g. Tyre sealant needs to be replaced/checked every 3 months regardless of how many hours you’ve been riding).

**Comment by Konstantin-Levin** [comment]
I would like to be able to set the service schedule to repeat every 3 months or 90 days for example from the start date of the latest usage period.
 
User would then receive a notification and it would be marked as overdue.
When the service has been recorded, the schedule should then reset and begin again for another 3 months. Thanks

**Comment by Gerben321** [comment]
I woud like to add that I am also planning to do a ride count interval type of schedule. So for example every single ride to clean your suspension fork for example. Or every 10 rides to check something else.

The time interval schedule will be in days I think. So set to 90 days for ~3 months like you said. Maybe I can get a selector for days/weeks/months or something. Have to investigate.

**Comment by Gerben321** [comment]
Here are some screenshots regarding time-based service interval:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/2d02c726-9b62-446a-96a4-92e892828088)
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/00b4b8dd-377b-444a-b586-9d5d2e6b19b2)
The remaining text will either show x hours left, x days left, or x months and x days left, depending on what interval you have selected.
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/a38568f8-4ef2-4287-a31a-59236fdb981b)
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/2bb642ba-40f5-4d71-a578-f6d20dc8e75b)

Next up is to build some script that checks for overdue time interval schedules. I think it would be fine if this runs maybe every hour. Unless you guys think getting the notification about overdue service is critical and should be checked more frequently, or maybe less?

**Comment by Konstantin-Levin** [comment]
Looking good so far. 
>Unless you guys think getting the notification about overdue service is critical and should be checked more frequently, or maybe less?

I think a check every hour sounds reasonable

**Comment by Gerben321** [comment]
This is now added! Let me know how it works for you.
