### ISSUE TITLE
Sorting of "From/Until" on the component usage period page

### ISSUE THREAD

**Issue by Konstantin-Levin** [Gerben321/bike-care-tracker#73]
**Describe the bug**
When clicking on the word _From_ or _Until_ to sort the dates into ascending/descending order the result does not appear to be correct. Is it being done alphabetically perhaps? Is this the expected behaviour - am I missing something here?

When clicking through so that neither is selected, the dates are then shown in the correct order

**To Reproduce**
Tried this on several different components with the same result

**Expected behavior**
The dates should be in the correct ascending or descending order.

**Screenshots**
<img width="1141" alt="Screenshot 2024-04-01 at 16 48 20" src="https://github.com/Gerben321/bike-care-tracker/assets/155573822/51a79a65-5a7f-4f0d-9126-38b423ff7de1">
<img width="1152" alt="Screenshot 2024-04-01 at 16 48 57" src="https://github.com/Gerben321/bike-care-tracker/assets/155573822/e7fce820-8699-47c9-873b-18ef76df9712">
<img width="1150" alt="Screenshot 2024-04-01 at 16 49 05" src="https://github.com/Gerben321/bike-care-tracker/assets/155573822/a6d0e53d-b740-4103-aa7d-6f1e30b6a2b3">

**Desktop (please complete the following information):**
Firefox desktop

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

Thanks

**Comment by Gerben321** [comment]
That's strange. I'll investigate that.

**Comment by Gerben321** [comment]
Should fixed now! Totally transformed the page with a different kind of table (data from server), to match all other tables. Should look and work the same though.
