### ISSUE TITLE
Idea: Quick action to delay a service schedule 

### ISSUE THREAD

**Issue by Konstantin-Levin** [Gerben321/bike-care-tracker#74]
One thing I’ve found that is missing from bike care and that is a feature of other apps is a function to delay a service schedule. This is something that happens to me frequently 

An example being: 
* An alert from a service schedule tells me it is time to check the wear on my brake pads. 
* After performing the check I realise they probably have another 500km of usage left in them at least.
* My regular service interval might be 2000km from new, so a delay rather than registering a full service would be helpful.
* This wouldn't affect anything about the intervals on future services, it should just delay the upcoming one
(Hope this makes sense) 

Of course this can be done 'manually' by editing the service schedule and changing the interval or the offset, but this feels a bit clumsy to me, and I then have to go back and edit the service again at some point. 

Maybe a dedicated button on the service schedule page which when clicked, shows a pop up allowing user to enter a distance or time to delay by?

<img width="404" alt="Screenshot 2024-04-12 at 17 13 05" src="https://github.com/Gerben321/bike-care-tracker/assets/155573822/657fd7ad-f11c-43c9-8fd1-2dd4a3bb4fbf">

Just a quick thought, there could be a better way to implement

**Comment by Gerben321** [comment]
Interesting idea. So this adds a certain amount in the current interval? So you can add either hours or km/mi depending on the type of schedule?

I assume this will be reset at the next service that you register? Is that how it works?

**Comment by Konstantin-Levin** [comment]
>Interesting idea. So this adds a certain amount in the current interval? So you can add either hours or km/mi depending on the type of schedule?

Yes I'm thinking of quite a simple pop which gives the user the option to delay only by whatever unit the service schedule was originally created with, be that hours/mi/km. 

As I said, I realise the user can just edit the _Offset (starts at)_ value to achieve the same effect, but I feel a 'delay' option would be easier to understand for the average user.

I don’t think there should be the option to change from a time to a distance interval here, as that is already easy to do in the _Edit service schedule_ page 


> I assume this will be reset at the next service that you register? Is that how it works?

Yes only the upcoming service schedule is delayed, after that everything else should resume as normal

**Comment by Gerben321** [comment]
Sounds good. I'll have a think about how to add this feature in the best way technically.

I haven't worked on bike care due to some more bike training for an upcoming event so I'm keen to get back to work on here!

**Comment by Gerben321** [comment]
I've updated the buttons a little:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/2d4e86a1-0820-4e0f-9de8-e1ab6aa8528b)
This should match the component list of buttons. Also, when you press the delay button you get this:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/442a1554-b572-45b4-9aa4-d2af7be20ec6)
This gives a popup with a field with a distance/time/ride count to delay the schedule. This simply adds that to the '... left' text and percentage. That's what it is supposed to do right?

So the result is this if I add 1 hour:
![image](https://github.com/Gerben321/bike-care-tracker/assets/24865452/6195a97d-a093-41b0-b1f6-26ff0c6a113d)

So if you have 20 hours left, and you delay it with 2 hours, you get 22 hours left. Same with distance or ride count.

Right now the delay can only be removed by registering new service. Maybe when you've got a delay I can also make a button that says 'remove delay' in case you want to get rid of it. 🤔

Let me know what you think so far. I've also updated the way the percentages are calculated, so it's an important change that we have to test properly to see if no percentages are calculated wrongly now. Once I've done some more testing and you think it's looking good I will publish the update.

**Comment by Konstantin-Levin** [comment]
That looks great, exactly what I had in mind! Thanks! 

Perhaps the only small thing I'd change is the wording on the delay pop-up box just to make it absolutely clear. It could say something like "How long do you want to delay this service by" or "Choose how long to delay this service by" 


> Maybe when you've got a delay I can also make a button that says 'remove delay' in case you want to get rid of it.

I don’t have a strong opinion either way... If the user had set a delay and the same _Delay service_ button just changed to _Remove delay_ that would keep things looking clean.

One question I have is: will the option to delay the service be available regardless of status? That is to say whether it is good/almost overdue/overdue?
In my thinking it would only show on an almost overdue/overdue service, but I guess it doesn't really matter? 



Nice idea matching up the buttons to the component style 👍

**Comment by Gerben321** [comment]
Good idea about the text, I'll add something there. Right now the button is always visible. It can't hurt I guess. 🤷🏻‍♂️

**Comment by Gerben321** [comment]
I've added the text and changed the button. You can try it out now. Let me know what you think!

**Comment by Konstantin-Levin** [comment]
I've had a play around with it. Looks to be working well - just what I needed. Many thanks!
